apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: {{ .Values.gvisor.runtimeClassName }}
handler: {{ .Values.gvisor.runtimeHandler }}
scheduling:
  nodeSelector: {{ toYaml .Values.gvisor.nodeSelector | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "insight-platform-sandbox.gvisorName" . }}
  namespace: {{ .Values.namespaces.guest }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "watch", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "insight-platform-sandbox.gvisorName" . }}
  namespace: {{ .Values.namespaces.guest }}
subjects:
  - kind: ServiceAccount
    name: {{ include "insight-platform-sandbox.gvisorName" . }}
    namespace: {{ .Values.namespaces.executor }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "insight-platform-sandbox.gvisorName" . }}
