apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "insight-platform-sandbox.controllerName" . }}
  namespace: {{ .Values.namespaces.controller }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "insight-platform-sandbox.gvisorName" . }}
  namespace: {{ .Values.namespaces.executor }}
  annotations:
    {{- toYaml .Values.gvisor.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gvisor.guestServiceAccount }}
  namespace: {{ .Values.namespaces.guest }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "insight-platform-sandbox.executorName" . }}
  namespace: {{ .Values.namespaces.executor }}
  annotations:
    {{- toYaml .Values.executor.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "insight-platform-sandbox.attestorName" . }}
  namespace: {{ .Values.namespaces.executor }}
automountServiceAccountToken: false
