apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "insight-platform-sandbox.controllerName" . }}
  namespace: {{ .Values.namespaces.controller }}
  annotations:
    {{- toYaml .Values.controller.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "insight-platform-sandbox.microVmExecutorName" . }}
  namespace: {{ .Values.namespaces.executor }}
  annotations:
    {{- toYaml .Values.microVmExecutor.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "insight-platform-sandbox.executorName" . }}
  namespace: {{ .Values.namespaces.executor }}
  annotations:
    {{- toYaml .Values.executor.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "insight-platform-sandbox.attestorName" . }}
  namespace: {{ .Values.namespaces.executor }}
automountServiceAccountToken: false
