[package]
name = "insight-platform-orchestrator"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
chrono.workspace = true
insight-platform-contracts.workspace = true
insight-platform-jobs.workspace = true
serde.workspace = true
serde_json.workspace = true
