{{- if .Values.monitoring.enabled }}
{{- $root := . -}}
{{ range $role, $_ := .Values.roles }}
{{- $ctx := dict "root" $root "role" $role }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "insight-platform-gateway.name" $ctx }}
  namespace: {{ $root.Values.namespace }}
  labels: {{ include "insight-platform-gateway.labels" $ctx | nindent 4 }}
spec:
  namespaceSelector: {matchNames: [{{ $root.Values.namespace }}]}
  selector:
    matchLabels: {{ include "insight-platform-gateway.labels" $ctx | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ $root.Values.monitoring.interval }}
      scrapeTimeout: {{ $root.Values.monitoring.scrapeTimeout }}
      scheme: http
---
{{ end }}
{{- end }}
