apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.egress }}
  labels:
    insight.platform/egress-namespace: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.securityAuthority }}
  labels:
    insight.platform/security-authority-namespace: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
