{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "insight-platform-security-egress.egressName" . }}
  namespace: {{ .Values.namespaces.egress }}
spec:
  minAvailable: {{ int .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: egress-broker
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "insight-platform-security-egress.authorityName" . }}
  namespace: {{ .Values.namespaces.securityAuthority }}
spec:
  minAvailable: {{ int .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: security-authority
{{- end }}
