apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "insight-platform-security-egress.egressName" . }}
  namespace: {{ .Values.namespaces.egress }}
  annotations:
    {{- toYaml .Values.egress.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "insight-platform-security-egress.authorityName" . }}
  namespace: {{ .Values.namespaces.securityAuthority }}
automountServiceAccountToken: false
