[package]
name = "insight-platform-rpc-trace"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
insight-platform-execution-context.workspace = true
insight-platform-contracts.workspace = true
tonic.workspace = true

[dev-dependencies]
tracing.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
