//! Exact process environments shared by CLI supervision and direct container entrypoints.
use crate::{
    base_profile::*,
    full_profile::{self, ProcessLaunch, ProcessPaths, *},
    tls::*,
};
use insight_platform_deployment_contracts::installation::{
    InstallationError, InstallationProcess as Process, NetworkTopologyV1,
};
use std::path::Path;
/// Values are already selected by the adapter; this type never exposes a Debug representation.
pub struct ProcessDatabaseUrls<'a> {
    pub primary: &'a str,
    pub read: Option<&'a str>,
    pub work: Option<&'a str>,
}
pub struct ProcessEnvironmentInputs<'a> {
    pub process: Process,
    pub paths: ProcessPaths<'a>,
    pub network: &'a NetworkTopologyV1,
    pub configuration_digest: &'a str,
    pub database: ProcessDatabaseUrls<'a>,
    pub cursor_key_path: Option<&'a Path>,
    pub cursor_key_digest: Option<&'a str>,
    pub aws_credentials_path: Option<&'a Path>,
}
pub fn process_launch(
    inputs: ProcessEnvironmentInputs<'_>,
) -> Result<ProcessLaunch, InstallationError> {
    inputs.network.validate()?;
    let paths = &inputs.paths;
    let _: insight_platform_contracts::Sha256Digest = inputs
        .configuration_digest
        .parse()
        .map_err(|_| InstallationError::InvalidInput)?;
    let mut environment = match inputs.process {
        Process::ContextNative => vec![
            (
                "PLATFORM_CONTEXT_WORKER_CONFIG",
                paths
                    .configuration
                    .join(CONTEXT_NATIVE_CONFIG_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_CONTEXT_WORKER_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_CONTEXT_WORKER_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
        ],
        Process::ArtifactMaintenance => vec![
            (
                "PLATFORM_ARTIFACT_MAINTENANCE_CONFIG",
                paths
                    .configuration
                    .join(ARTIFACT_MAINTENANCE_CONFIG_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_ARTIFACT_MAINTENANCE_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_ARTIFACT_MAINTENANCE_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
        ],
        Process::SecurityAuthority => vec![
            (
                "PLATFORM_SECURITY_AUTHORITY_CONFIG",
                paths
                    .configuration
                    .join(SECURITY_AUTHORITY_CONFIG_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_SECURITY_AUTHORITY_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_SECURITY_AUTHORITY_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
            (
                "PLATFORM_SECURITY_AUTHORITY_CLIENT_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_SECURITY_AUTHORITY_CERT_PATH",
                paths
                    .tls
                    .join(SECURITY_AUTHORITY_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_SECURITY_AUTHORITY_KEY_PATH",
                paths
                    .tls
                    .join(SECURITY_AUTHORITY_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
        ],
        Process::EgressBroker => vec![
            (
                "PLATFORM_EGRESS_BROKER_CONFIG",
                paths
                    .configuration
                    .join(EGRESS_BROKER_CONFIG_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_EGRESS_BROKER_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_EGRESS_BROKER_AUTHORITY_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_EGRESS_BROKER_AUTHORITY_CERT_PATH",
                paths
                    .tls
                    .join(EGRESS_BROKER_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_EGRESS_BROKER_AUTHORITY_KEY_PATH",
                paths
                    .tls
                    .join(EGRESS_BROKER_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_EGRESS_BROKER_CLIENT_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_EGRESS_BROKER_CERT_PATH",
                paths
                    .tls
                    .join(EGRESS_BROKER_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_EGRESS_BROKER_KEY_PATH",
                paths
                    .tls
                    .join(EGRESS_BROKER_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
        ],
        Process::ModelWorker => vec![
            (
                "PLATFORM_MODEL_WORKER_CONFIG",
                paths
                    .configuration
                    .join(MODEL_WORKER_CONFIG_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MODEL_WORKER_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_MODEL_WORKER_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
            (
                "PLATFORM_MODEL_WORKER_EGRESS_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MODEL_WORKER_EGRESS_CERT_PATH",
                paths
                    .tls
                    .join(MODEL_WORKER_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MODEL_WORKER_EGRESS_KEY_PATH",
                paths
                    .tls
                    .join(MODEL_WORKER_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MODEL_WORKER_NATS_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MODEL_WORKER_NATS_CERT_PATH",
                paths
                    .tls
                    .join(paths.nats_client_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MODEL_WORKER_NATS_KEY_PATH",
                paths
                    .tls
                    .join(paths.nats_client_private_key_file)
                    .display()
                    .to_string(),
            ),
        ],
        Process::ContextRemote => vec![
            (
                "PLATFORM_REMOTE_CONTEXT_WORKER_CONFIG",
                paths
                    .configuration
                    .join(CONTEXT_REMOTE_CONFIG_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_REMOTE_CONTEXT_WORKER_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_REMOTE_CONTEXT_WORKER_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
            (
                "PLATFORM_REMOTE_CONTEXT_WORKER_EGRESS_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_REMOTE_CONTEXT_WORKER_EGRESS_CERT_PATH",
                paths
                    .tls
                    .join(CONTEXT_WORKER_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_REMOTE_CONTEXT_WORKER_EGRESS_KEY_PATH",
                paths
                    .tls
                    .join(CONTEXT_WORKER_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
        ],
        Process::McpHost => vec![
            (
                "PLATFORM_MCP_HOST_CONFIG",
                paths
                    .configuration
                    .join(MCP_HOST_CONFIG_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_HOST_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_MCP_HOST_SERVER_CLIENT_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_HOST_SERVER_CERT_PATH",
                paths
                    .tls
                    .join(MCP_HOST_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_HOST_SERVER_KEY_PATH",
                paths
                    .tls
                    .join(MCP_HOST_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_HOST_EGRESS_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_HOST_EGRESS_CERT_PATH",
                paths
                    .tls
                    .join(MCP_HOST_EGRESS_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_HOST_EGRESS_KEY_PATH",
                paths
                    .tls
                    .join(MCP_HOST_EGRESS_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
        ],
        Process::McpResourceHost => vec![
            (
                "PLATFORM_MCP_RESOURCE_HOST_CONFIG",
                paths
                    .configuration
                    .join(MCP_RESOURCE_HOST_CONFIG_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_RESOURCE_HOST_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_MCP_RESOURCE_HOST_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
            (
                "PLATFORM_MCP_RESOURCE_HOST_SERVER_CLIENT_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_RESOURCE_HOST_SERVER_CERT_PATH",
                paths
                    .tls
                    .join(MCP_RESOURCE_HOST_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_RESOURCE_HOST_SERVER_KEY_PATH",
                paths
                    .tls
                    .join(MCP_RESOURCE_HOST_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_RESOURCE_HOST_EGRESS_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_RESOURCE_HOST_EGRESS_CERT_PATH",
                paths
                    .tls
                    .join(MCP_RESOURCE_EGRESS_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_RESOURCE_HOST_EGRESS_KEY_PATH",
                paths
                    .tls
                    .join(MCP_RESOURCE_EGRESS_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
        ],
        Process::CapabilityRemote => vec![
            (
                "PLATFORM_CAPABILITY_REMOTE_WORKER_CONFIG",
                paths
                    .configuration
                    .join(CAPABILITY_REMOTE_CONFIG_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_CAPABILITY_REMOTE_WORKER_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_CAPABILITY_REMOTE_WORKER_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
            (
                "PLATFORM_CAPABILITY_REMOTE_WORKER_EGRESS_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_CAPABILITY_REMOTE_WORKER_EGRESS_CERT_PATH",
                paths
                    .tls
                    .join(CAPABILITY_REMOTE_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_CAPABILITY_REMOTE_WORKER_EGRESS_KEY_PATH",
                paths
                    .tls
                    .join(CAPABILITY_REMOTE_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_CAPABILITY_REMOTE_WORKER_MCP_HOST_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_CAPABILITY_REMOTE_WORKER_MCP_HOST_CERT_PATH",
                paths
                    .tls
                    .join(CAPABILITY_REMOTE_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_CAPABILITY_REMOTE_WORKER_MCP_HOST_KEY_PATH",
                paths
                    .tls
                    .join(CAPABILITY_REMOTE_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
        ],
        Process::McpDiscovery => vec![
            (
                "PLATFORM_MCP_DISCOVERY_WORKER_CONFIG",
                paths
                    .configuration
                    .join(MCP_DISCOVERY_CONFIG_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_DISCOVERY_WORKER_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_MCP_DISCOVERY_WORKER_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
            (
                "PLATFORM_MCP_DISCOVERY_WORKER_CLIENT_CERT_PATH",
                paths
                    .tls
                    .join(MCP_DISCOVERY_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_DISCOVERY_WORKER_CLIENT_KEY_PATH",
                paths
                    .tls
                    .join(MCP_DISCOVERY_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_DISCOVERY_WORKER_EGRESS_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_DISCOVERY_WORKER_ARTIFACT_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
        ],
        Process::McpSubscription => vec![
            (
                "PLATFORM_MCP_SUBSCRIPTION_WORKER_CONFIG",
                paths
                    .configuration
                    .join(MCP_SUBSCRIPTION_CONFIG_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_SUBSCRIPTION_WORKER_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_MCP_SUBSCRIPTION_WORKER_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
            (
                "PLATFORM_MCP_SUBSCRIPTION_WORKER_CLIENT_CERT_PATH",
                paths
                    .tls
                    .join(MCP_SUBSCRIPTION_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_SUBSCRIPTION_WORKER_CLIENT_KEY_PATH",
                paths
                    .tls
                    .join(MCP_SUBSCRIPTION_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_SUBSCRIPTION_WORKER_EGRESS_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
        ],
        Process::McpCleanup => vec![
            (
                "PLATFORM_MCP_CLEANUP_CONFIG",
                paths
                    .configuration
                    .join(MCP_CLEANUP_CONFIG_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_CLEANUP_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_MCP_CLEANUP_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
            (
                "PLATFORM_MCP_CLEANUP_EGRESS_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_CLEANUP_EGRESS_CERT_PATH",
                paths
                    .tls
                    .join(MCP_CLEANUP_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_MCP_CLEANUP_EGRESS_KEY_PATH",
                paths
                    .tls
                    .join(MCP_CLEANUP_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
        ],
        Process::ContextSubscription => vec![
            (
                "PLATFORM_SUBSCRIPTION_CONTEXT_WORKER_CONFIG",
                paths
                    .configuration
                    .join(CONTEXT_SUBSCRIPTION_CONFIG_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_SUBSCRIPTION_CONTEXT_WORKER_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_SUBSCRIPTION_CONTEXT_WORKER_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
            (
                "PLATFORM_SUBSCRIPTION_CONTEXT_WORKER_HOST_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_SUBSCRIPTION_CONTEXT_WORKER_HOST_CERT_PATH",
                paths
                    .tls
                    .join(CONTEXT_SUBSCRIPTION_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_SUBSCRIPTION_CONTEXT_WORKER_HOST_KEY_PATH",
                paths
                    .tls
                    .join(CONTEXT_SUBSCRIPTION_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
        ],
        Process::CallbackApi => vec![
            (
                "PLATFORM_CALLBACK_API_CONFIG",
                paths
                    .configuration
                    .join(CALLBACK_API_CONFIG_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_CALLBACK_API_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_CALLBACK_API_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
            (
                "PLATFORM_CALLBACK_API_EGRESS_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_CALLBACK_API_EGRESS_CERT_PATH",
                paths
                    .tls
                    .join(CALLBACK_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_CALLBACK_API_EGRESS_KEY_PATH",
                paths
                    .tls
                    .join(CALLBACK_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
        ],
        Process::ContextDataset => vec![
            (
                "PLATFORM_CONTEXT_DATASET_WORKER_CONFIG",
                paths
                    .configuration
                    .join(CONTEXT_DATASET_CONFIG_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_CONTEXT_DATASET_WORKER_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_CONTEXT_DATASET_WORKER_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
            (
                "PLATFORM_CONTEXT_DATASET_WORKER_ARTIFACT_CA_PATH",
                paths
                    .tls
                    .join(paths.ca_certificate_file)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_CONTEXT_DATASET_WORKER_CLIENT_CERT_PATH",
                paths
                    .tls
                    .join(CONTEXT_DATASET_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_CONTEXT_DATASET_WORKER_CLIENT_KEY_PATH",
                paths
                    .tls
                    .join(CONTEXT_DATASET_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
        ],
        Process::ArtifactData => vec![
            (
                "PLATFORM_ARTIFACT_DATA_WORKER_CONFIG",
                config_path(paths.configuration, RUNTIME_ARTIFACT_DATA_CONFIG_FILE),
            ),
            (
                "PLATFORM_ARTIFACT_DATA_WORKER_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_ARTIFACT_DATA_WORKER_AUDIENCE",
                "data_worker".to_owned(),
            ),
            (
                "PLATFORM_ARTIFACT_DATA_WORKER_READ_DATABASE_URL",
                inputs
                    .database
                    .read
                    .ok_or(InstallationError::CredentialInvalid)?
                    .to_owned(),
            ),
            (
                "PLATFORM_ARTIFACT_DATA_WORKER_WORK_DATABASE_URL",
                inputs
                    .database
                    .work
                    .ok_or(InstallationError::CredentialInvalid)?
                    .to_owned(),
            ),
            (
                "PLATFORM_ARTIFACT_DATA_WORKER_CLIENT_CA_PATH",
                paths
                    .tls
                    .join(RUNTIME_CA_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_ARTIFACT_DATA_WORKER_CERT_PATH",
                paths
                    .tls
                    .join(RUNTIME_ARTIFACT_DATA_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_ARTIFACT_DATA_WORKER_KEY_PATH",
                paths
                    .tls
                    .join(RUNTIME_ARTIFACT_DATA_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
        ],
        Process::ArtifactGateway => vec![
            (
                "PLATFORM_ARTIFACT_GATEWAY_CONFIG",
                config_path(paths.configuration, RUNTIME_ARTIFACT_GATEWAY_CONFIG_FILE),
            ),
            (
                "PLATFORM_ARTIFACT_GATEWAY_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_ARTIFACT_GATEWAY_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
            (
                "PLATFORM_ARTIFACT_GATEWAY_CLIENT_CA_PATH",
                paths
                    .tls
                    .join(RUNTIME_CA_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_ARTIFACT_GATEWAY_CERT_PATH",
                paths
                    .tls
                    .join(RUNTIME_ARTIFACT_GATEWAY_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_ARTIFACT_GATEWAY_KEY_PATH",
                paths
                    .tls
                    .join(RUNTIME_ARTIFACT_GATEWAY_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
        ],
        Process::Orchestration => vec![
            (
                "PLATFORM_ORCHESTRATION_WORKER_CONFIG",
                config_path(paths.configuration, RUNTIME_ORCHESTRATION_CONFIG_FILE),
            ),
            (
                "PLATFORM_ORCHESTRATION_WORKER_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_ORCHESTRATION_WORKER_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
            (
                "PLATFORM_ORCHESTRATION_WORKER_ARTIFACT_CA_PATH",
                paths
                    .tls
                    .join(RUNTIME_CA_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_ORCHESTRATION_WORKER_ARTIFACT_CERT_PATH",
                paths
                    .tls
                    .join(RUNTIME_ORCHESTRATION_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_ORCHESTRATION_WORKER_ARTIFACT_KEY_PATH",
                paths
                    .tls
                    .join(RUNTIME_ORCHESTRATION_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
        ],
        Process::CapabilityNative => vec![
            (
                "PLATFORM_CAPABILITY_NATIVE_WORKER_CONFIG",
                config_path(paths.configuration, RUNTIME_CAPABILITY_NATIVE_CONFIG_FILE),
            ),
            (
                "PLATFORM_CAPABILITY_NATIVE_WORKER_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_CAPABILITY_NATIVE_WORKER_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
        ],
        Process::RegistryValidation => vec![
            (
                "PLATFORM_REGISTRY_VALIDATION_WORKER_CONFIG",
                config_path(paths.configuration, RUNTIME_REGISTRY_VALIDATION_CONFIG_FILE),
            ),
            (
                "PLATFORM_REGISTRY_VALIDATION_WORKER_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_REGISTRY_VALIDATION_WORKER_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
            (
                "PLATFORM_REGISTRY_VALIDATION_ARTIFACT_ENDPOINT",
                inputs.network.endpoint(Process::ArtifactGateway)?,
            ),
            (
                "PLATFORM_REGISTRY_VALIDATION_ARTIFACT_CA_PATH",
                paths
                    .tls
                    .join(RUNTIME_CA_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_REGISTRY_VALIDATION_ARTIFACT_CERT_PATH",
                paths
                    .tls
                    .join(RUNTIME_REGISTRY_VALIDATION_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_REGISTRY_VALIDATION_ARTIFACT_KEY_PATH",
                paths
                    .tls
                    .join(RUNTIME_REGISTRY_VALIDATION_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
        ],
        Process::GatewayManagement => vec![
            (
                "PLATFORM_GATEWAY_CONFIG",
                config_path(paths.configuration, RUNTIME_GATEWAY_MANAGEMENT_CONFIG_FILE),
            ),
            (
                "PLATFORM_GATEWAY_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_GATEWAY_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
            (
                "PLATFORM_GATEWAY_EGRESS_CA_PATH",
                paths
                    .tls
                    .join(RUNTIME_CA_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_GATEWAY_EGRESS_CERT_PATH",
                paths
                    .tls
                    .join(full_profile::GATEWAY_EGRESS_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_GATEWAY_EGRESS_KEY_PATH",
                paths
                    .tls
                    .join(full_profile::GATEWAY_EGRESS_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_GATEWAY_RUN_EVENT_CURSOR_KEY_PATH",
                inputs
                    .cursor_key_path
                    .ok_or(InstallationError::CredentialInvalid)?
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_GATEWAY_RUN_EVENT_CURSOR_KEY_DIGEST",
                inputs
                    .cursor_key_digest
                    .ok_or(InstallationError::CredentialInvalid)?
                    .to_owned(),
            ),
            (
                "PLATFORM_GATEWAY_ARTIFACT_CA_PATH",
                paths
                    .tls
                    .join(RUNTIME_CA_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_GATEWAY_ARTIFACT_CERT_PATH",
                paths
                    .tls
                    .join(RUNTIME_GATEWAY_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_GATEWAY_ARTIFACT_KEY_PATH",
                paths
                    .tls
                    .join(RUNTIME_GATEWAY_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
        ],
        Process::GatewayRuntime => vec![
            (
                "PLATFORM_GATEWAY_CONFIG",
                config_path(paths.configuration, RUNTIME_GATEWAY_RUNTIME_CONFIG_FILE),
            ),
            (
                "PLATFORM_GATEWAY_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_GATEWAY_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
            (
                "PLATFORM_GATEWAY_RUN_EVENT_CURSOR_KEY_PATH",
                inputs
                    .cursor_key_path
                    .ok_or(InstallationError::CredentialInvalid)?
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_GATEWAY_RUN_EVENT_CURSOR_KEY_DIGEST",
                inputs
                    .cursor_key_digest
                    .ok_or(InstallationError::CredentialInvalid)?
                    .to_owned(),
            ),
            (
                "PLATFORM_GATEWAY_ARTIFACT_CA_PATH",
                paths
                    .tls
                    .join(RUNTIME_CA_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_GATEWAY_ARTIFACT_CERT_PATH",
                paths
                    .tls
                    .join(RUNTIME_GATEWAY_CLIENT_CERTIFICATE_FILE)
                    .display()
                    .to_string(),
            ),
            (
                "PLATFORM_GATEWAY_ARTIFACT_KEY_PATH",
                paths
                    .tls
                    .join(RUNTIME_GATEWAY_CLIENT_PRIVATE_KEY_FILE)
                    .display()
                    .to_string(),
            ),
        ],
        Process::Outbox => vec![
            (
                "PLATFORM_OUTBOX_CONFIG",
                config_path(paths.configuration, OUTBOX_CONFIG_FILE),
            ),
            (
                "PLATFORM_OUTBOX_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_OUTBOX_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
            (
                "PLATFORM_OUTBOX_NATS_CA_PATH",
                config_path(paths.tls, paths.ca_certificate_file),
            ),
            (
                "PLATFORM_OUTBOX_NATS_CERT_PATH",
                config_path(paths.tls, "outbox-client.pem"),
            ),
            (
                "PLATFORM_OUTBOX_NATS_KEY_PATH",
                config_path(paths.tls, "outbox-client-key.pem"),
            ),
        ],
        Process::HistoryMaintenance => vec![
            (
                "PLATFORM_HISTORY_MAINTENANCE_CONFIG",
                config_path(paths.configuration, HISTORY_CONFIG_FILE),
            ),
            (
                "PLATFORM_HISTORY_MAINTENANCE_CONFIG_DIGEST",
                inputs.configuration_digest.to_owned(),
            ),
            (
                "PLATFORM_HISTORY_MAINTENANCE_DATABASE_URL",
                inputs.database.primary.to_owned(),
            ),
        ],
    };
    if inputs.process == Process::CapabilityRemote
        && inputs.network.process(Process::McpHost).is_err()
    {
        environment
            .retain(|(key, _)| !key.starts_with("PLATFORM_CAPABILITY_REMOTE_WORKER_MCP_HOST_"));
    }
    let mut extra_environment = if matches!(
        inputs.process,
        Process::ArtifactData
            | Process::ArtifactGateway
            | Process::ArtifactMaintenance
            | Process::EgressBroker
    ) && !(inputs.process == Process::EgressBroker
        && matches!(
            inputs.network.providers,
            insight_platform_deployment_contracts::installation::ProviderNetworkV1::S3OpenBao { .. }
        )) {
        if let Some(path) = inputs.aws_credentials_path {
            let name = if matches!(
                inputs.network.providers,
                insight_platform_deployment_contracts::installation::ProviderNetworkV1::S3OpenBao { .. }
            ) {
                format!("s3-{}-credentials", inputs.process.name())
            } else {
                "aws-credentials".into()
            };
            if path != paths.tls.join(name) {
                return Err(InstallationError::CredentialInvalid);
            }
            vec![
                (
                    "AWS_SHARED_CREDENTIALS_FILE".into(),
                    path.display().to_string(),
                ),
                ("AWS_PROFILE".into(), "default".into()),
                ("AWS_EC2_METADATA_DISABLED".into(), "true".into()),
            ]
        } else {
            if matches!(
                inputs.network.providers,
                insight_platform_deployment_contracts::installation::ProviderNetworkV1::S3OpenBao { .. }
            ) {
                return Err(InstallationError::CredentialInvalid);
            }
            [
                ("AWS_ACCESS_KEY_ID", "test"),
                ("AWS_SECRET_ACCESS_KEY", "test"),
                ("AWS_EC2_METADATA_DISABLED", "true"),
            ]
            .into_iter()
            .map(|(key, value)| (key.to_owned(), value.to_owned()))
            .collect()
        }
    } else {
        Vec::new()
    };
    if crate::role_material::requires_aws_ca(inputs.network, inputs.process) {
        extra_environment.push((
            "SSL_CERT_FILE".into(),
            paths.tls.join("ca.pem").display().to_string(),
        ));
        extra_environment.push(("SSL_CERT_DIR".into(), "/etc/ssl/certs".into()));
    }
    Ok(ProcessLaunch {
        role: inputs.process.name(),
        binary: paths.release.join(format!(
            "{}{}",
            inputs.process.binary(),
            std::env::consts::EXE_SUFFIX
        )),
        ready_address: inputs.network.observability(inputs.process)?,
        environment,
        extra_environment,
    })
}
fn config_path(directory: &Path, file: &str) -> String {
    directory.join(file).display().to_string()
}
