[package]
name = "insight-platform-sandbox-controller"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
insight-platform-artifact-broker.workspace = true
insight-platform-contracts.workspace = true
insight-platform-postgres.workspace = true
insight-platform-sandbox.workspace = true
insight-platform-sandbox-rpc.workspace = true
ipnet.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tonic.workspace = true

[[bin]]
name = "platform-sandbox-controller"
path = "src/main.rs"
